package com.example.xiaowu.greendao.generate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.xiaowu.greendao.Channel;
import com.example.xiaowu.greendao.Message;

import com.example.xiaowu.greendao.generate.ChannelDao;
import com.example.xiaowu.greendao.generate.MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final ChannelDao channelDao;
    private final MessageDao messageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        channelDao = new ChannelDao(channelDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(Channel.class, channelDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        channelDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
